name: SkycadeCustomItems
version: 1.1.1-SNAPSHOT
description: Skycade Custom Items
authors: ["Christian Doughty (Taon2)"]
main: net.skycade.skycadecustomitems.SkycadeCustomItemsPlugin
softdepend: [SkycadeShop, SkycadeEnchants, Prison]
depend: [SkycadeCore]