name: SkycadeCustomItems
version: 1.4.19-SNAPSHOT
description: Skycade Custom Items
authors: ["Christian Doughty (Taon2)"]
main: net.skycade.skycadecustomitems.SkycadeCustomItemsPlugin
softdepend: [SkycadeShop, SkycadeEnchants, Prison, SkycadeKOTH]
depend: [SkycadeCore]